- hosts: localhost
  tasks:
    - name: Inspect sphinx build directory
      find:
        file_type: any
        follow: true
        paths: "{{ zuul_work_dir }}/doc/build"
      register: sphinx_dir

    - name: Parse sphinx build directory
      set_fact:
        sphinx_dir: "{{ sphinx_dir.files | map(attribute='path') | map('regex_replace', '^.*/(.*)$', '\\1') | list }}"

    - name: debug
      debug:
        var: sphinx_dir
